from django.urls import path
from . import views

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path("novedades/", views.novedades, name="novedades"),
    path("productos/", views.productos, name="productos"),
    path("producto/<str:tipo>/<int:pk>/", views.detalle_producto, name="detalle_producto"),
    path("agregar-carrito/<str:tipo>/<int:pk>/", views.agregar_carrito, name="agregar_carrito"),
    path("carrito/", views.ver_carrito, name="carrito"),
    path("carrito/actualizar/", views.actualizar_carrito, name="actualizar_carrito"),
    path("carrito/eliminar/<str:clave>/", views.eliminar_item_carrito, name="eliminar_item_carrito"),
    path("pago/", views.procesar_pago, name="procesar_pago"),
    path("perfil/", views.perfil_usuario, name="perfil_usuario"),
    path("contacto/", views.contacto, name="contacto"),
    path("iniciar-sesion/", views.iniciar_sesion, name="iniciar_sesion"),
    path("cerrar-sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("registro/", views.registrarse, name="registrarse"),
    path("panel/", views.panel_admin, name="panel_admin"),
    path("cabello/", views.admin_cabello_lista, name="admin_cabello_lista"),
    path("cabello/nuevo/", views.admin_cabello_crear, name="admin_cabello_crear"),
    path("cabello/<int:pk>/editar/", views.admin_cabello_editar, name="admin_cabello_editar"),
    path("cabello/<int:pk>/eliminar/", views.admin_cabello_eliminar, name="admin_cabello_eliminar"),
    path("maquillaje/", views.admin_maquillaje_lista, name="admin_maquillaje_lista"),
    path("maquillaje/nuevo/", views.admin_maquillaje_crear, name="admin_maquillaje_crear"),
    path("maquillaje/<int:pk>/editar/", views.admin_maquillaje_editar, name="admin_maquillaje_editar"),
    path("maquillaje/<int:pk>/eliminar/", views.admin_maquillaje_eliminar, name="admin_maquillaje_eliminar"),
    path("piel/", views.admin_piel_lista, name="admin_piel_lista"),
    path("piel/nuevo/", views.admin_piel_crear, name="admin_piel_crear"),
    path("piel/<int:pk>/editar/", views.admin_piel_editar, name="admin_piel_editar"),
    path("piel/<int:pk>/eliminar/", views.admin_piel_eliminar, name="admin_piel_eliminar"),
    path("perfumes/", views.admin_perfumes_lista, name="admin_perfumes_lista"),
    path("perfumes/nuevo/", views.admin_perfumes_crear, name="admin_perfumes_crear"),
    path("perfumes/<int:pk>/editar/", views.admin_perfumes_editar, name="admin_perfumes_editar"),
    path("perfumes/<int:pk>/eliminar/", views.admin_perfumes_eliminar, name="admin_perfumes_eliminar"),
    path("usuarios/", views.admin_usuarios_lista, name="admin_usuarios_lista"),
    path("usuarios/nuevo/", views.admin_usuarios_crear, name="admin_usuarios_crear"),
    path("usuarios/<int:pk>/editar/", views.admin_usuarios_editar, name="admin_usuarios_editar"),
    path("usuarios/<int:pk>/eliminar/", views.admin_usuarios_eliminar, name="admin_usuarios_eliminar"),
    path("usuarios/<int:pk>/detalle/", views.admin_usuario_detalle, name="admin_usuario_detalle"),
    path("pedidos/", views.admin_pedidos_lista, name="admin_pedidos_lista"),
]