# Generated by Django 5.2.6 on 2025-12-03 04:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('categoria', models.CharField(max_length=80)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'cabello',
            },
        ),
        migrations.CreateModel(
            name='CuidadoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('categoria', models.CharField(max_length=80)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'cuidado_de_la_piel',
            },
        ),
        migrations.CreateModel(
            name='Maquillaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('categoria', models.CharField(max_length=80)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'maquillaje',
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('categoria', models.CharField(max_length=80)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'perfumes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('direccion', models.TextField()),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formapago', models.CharField(max_length=60)),
                ('envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('domicilio', models.TextField()),
                ('detalle', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_divine.usuario')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
    ]
